### ISSUE TITLE
About the requirement of GPUS

### ISSUE THREAD

**Issue by clee-jaist** [jinghuichen/BackwardSmoothing#1]
Hi Dr. Chen,

This is a amazing work. I am going to do some test of this repository, but I did not found some devices details in your paper. For example, how many 2080Ti of your experiment required, or the minimum GPU requirements. As you konw, the AT need so much computing resource, so I need to make sure my devices can satisfied it in advance.

**Comment by jinghuichen** [comment]
Thanks for your interest in our work! Typically it is suffice to use 2080Ti for small experiments such as CIFAR10/100. For larger ones such as Tiny-Imagenet, you may need GPUs with large memory size.

**Comment by clee-jaist** [comment]
> 

Understood. Thank you so much
